kind: pipeline
name: default

steps:
  - name: build-alpine
    image: plugins/docker:linux-amd64
    pull: always
    settings:
      dockerfile: Dockerfile-alpine
      daemon_off: false
      dry_run: true
      repo: docker.asperti.com/paspo/angry-squid
      tags:
        - latest
        - alpine-latest
    when:
      event:
        exclude:
        - tag

  - name: build-debian
    image: plugins/docker:linux-amd64
    pull: always
    settings:
      dockerfile: Dockerfile-debian
      daemon_off: false
      dry_run: true
      repo: docker.asperti.com/paspo/angry-squid
      tags:
        - debian-latest
    when:
      event:
        exclude:
        - tag
        
  - name: build_and_publish-alpine
    image: plugins/docker:linux-amd64
    pull: always
    settings:
      dockerfile: Dockerfile-alpine
      auto_tag: true
      auto_tag_suffix: alpine
      daemon_off: false
      password:
        from_secret: docker_password
      registry: docker.asperti.com
      repo: docker.asperti.com/paspo/angry-squid
      tags:
        - latest
        - alpine-latest
      username:
        from_secret: docker_username
    when:
      event:
      - tag

  - name: build_and_publish-debian
    image: plugins/docker:linux-amd64
    pull: always
    settings:
      dockerfile: Dockerfile-debian
      auto_tag: true
      auto_tag_suffix: debian
      daemon_off: false
      password:
        from_secret: docker_password
      registry: docker.asperti.com
      repo: docker.asperti.com/paspo/angry-squid
      tags:
        - debian-latest
      username:
        from_secret: docker_username
    when:
      event:
      - tag